# Generated by Django 3.2.20 on 2023-08-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimg',
            field=models.ImageField(blank=True, upload_to='profileimg/%Y/%m/%d'),
        ),
    ]
