# Generated by Django 3.2.20 on 2023-08-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profileimg',
        ),
    ]
