# Generated by Django 3.2.20 on 2023-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='profileimg',
            field=models.ImageField(blank=True, upload_to='profileimg/%Y/%m/%d'),
        ),
    ]
