# Generated by Django 4.2.3 on 2023-07-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_contents_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
